# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.6.2'
      
    - name: Build with Gradle
      run: gradle build
      
    # 提取JAR文件并重命名为psqq_Additional_extras.jar
    - name: Extract and rename JAR file
      id: extract-jar
      run: |
        mkdir -p jar-output
        JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-sources.jar" -not -name "*-dev.jar" | head -n 1)
        if [ -z "$JAR_FILE" ]; then
          echo "No JAR file found!"
          exit 1
        fi
        echo "Found JAR file: $JAR_FILE"
        cp "$JAR_FILE" jar-output/psqq_Additional_extras.jar
        echo "Original JAR file was copied to jar-output/psqq_Additional_extras.jar"
        ls -la jar-output/
      
    # 上传重命名后的JAR文件作为构建产物
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: psqq_Additional_extras.jar
        path: jar-output/psqq_Additional_extras.jar
        if-no-files-found: error
